micronaut:
  application:
    name: pixKeymanagerGrpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix_keymanager_grpc
    driverClassName: org.postgresql.Driver
    username: root
    password: 123457
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bc:
  pix:
    url: 'http://localhost:8082'