micronaut:
  application:
    name: pixKeymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix_keymanager_grpc?useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bc:
  pix:
    url: 'http://localhost:8082'